const people = ["Greg", "Mary", "Devon", "James"];
people.shift()
people.pop()
people.unshift("Matt")
people.push("James")
const newArr = people.slice(2)
people.indexOf("Mary")
people.indexOf("Foo")
people.splice(0)
people.splice(0, 0, "Greg", "Mary", "Devon", "James")
people.splice(2, 1, "Elizabeth", "Artie")
const withBob = people.concat("Bob")
